# Generated by Django 4.2.4 on 2023-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_passenger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('city',), 'verbose_name': 'Аэропорт', 'verbose_name_plural': 'Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ('origin', 'duration'), 'verbose_name': 'Вылет', 'verbose_name_plural': 'Вылеты'},
        ),
        migrations.AddField(
            model_name='passenger',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(related_name='passanger_flights', to='flights.flight', verbose_name='Вылеты'),
        ),
    ]
