# Generated by Django 4.2.4 on 2023-09-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_airport_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('post', models.CharField(max_length=60, verbose_name='Должность')),
            ],
        ),
    ]
