# Generated by Django 4.2.4 on 2023-08-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=30, verbose_name='Тема поста')),
                ('posttext', models.CharField(max_length=30, verbose_name='Текст')),
            ],
        ),
    ]
