# Generated by Django 4.2.4 on 2023-08-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_alter_post_posttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postcomm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_postcomment', to='post.post', verbose_name='Комментируемый пост'),
        ),
    ]
